### ISSUE TITLE
Chapter 6, Page 145, paragraph 2, line 2

### ISSUE THREAD

**Issue by MudassarBashir** [GrailsInAction/graina2#126]
The line starts with:

"Because the control is named content,..."

is the word 'control' in this line referring to the g:textArea or is this some kind of a typo?

**Comment by pledbrook** [comment]
Yes. It's a common Windows term for user interface elements such as text fields, list boxes, etc.

**Comment by MudassarBashir** [comment]
Understood, thanks.
