### ISSUE TITLE
Page 159 first sentence

### ISSUE THREAD

**Issue by MudassarBashir** [GrailsInAction/graina2#128]
The first sentence on page 159 reads as:

When exceptions are thrown that are part of your anticipated business logic, it’d be
handy to reason about those exceptions.

Is this sentence trying to say it would be nice to know the reason why an exception is thrown? Is there a typo or am I missing something? Thanks.

**Comment by glenasmith** [comment]
Thanks for reporting. I think that is the correct sentence. When exceptions are thrown, Spock provides the thrown() keyword to help you assert the correct exception subclass is being thrown.

**Comment by MudassarBashir** [comment]
Understood. Thank you very much.
