### ISSUE TITLE
MEAP v13, ch6, Issues with PostControllerSpec (Listing 6.x, Pg. 144)

### ISSUE THREAD

**Issue by tikeswar** [GrailsInAction/graina2#64]
The test passes the first two tests <code>flash.message == "Successfully created Post"</code> and <code>response.redirectedUrl == "/post/timeline/${chuck.loginId}"</code>, but fails at the last line <code>Post.countByUser(chuck) == 1</code>. I get the following:

<pre>
|  Condition not satisfied:
Post.countByUser(chuck) == 1
     |           |      |
     0           |      false
                 grailstuts.User : 1
</pre>

The test result above is very puzzling and does not make sense to me. What the book says in the comment (// Ensure the post ended up in the DB), I think that makes more sense. However I have spent quite a bit of time trying to figure out the bug, but no luck yet. 

Any help will be highly appreciated. Thank you!

**Comment by ifrankov** [comment]
Hi Peter,

I have a java 8 and grails version 2.4.3 and I have the same problem.
When I try to create post. I recieve that post is created , but no post is created. 
If I add post.save() than post is created.

Post createPost(String loginId, String content) {
		println "tst"
		def user = User.findByLoginId(loginId)
		if (user) {
			def post = new Post(content: content)
			user.addToPosts(post)
			if (post.validate() && user.save()) {
				post.save()
				return post
			} else {
				throw new PostException(
					message: "Invalid or empty post", post: post)
			}
		}
		throw new PostException(message: "Invalid User Id")
	}
if there is no post.save() no post is saved.

I hope that you will give me a solution.

Thank you very much in advance!

Best regards,
Ivo

**Comment by ifrankov** [comment]
Hi if I use if (post.validate() && user.save(flush: true, failOnError: true)) {
Than it is ok. But it is strange becuase in BootStrap it is functioining without problems.

Post createPost(String loginId, String content) {
		println "tst"
		def user = User.findByLoginId(loginId)
		if (user) {
			def post = new Post(content: content)
			user.addToPosts(post)
			if (post.validate() && user.save(flush: true, failOnError: true)) {
			//post.save()
				return post
			} else {
				throw new PostException(
					message: "Invalid or empty post", post: post)
			}
		}
		throw new PostException(message: "Invalid User Id")
	}

**Comment by pledbrook** [comment]
@ifrankov Unfortunately I can't reproduce this issue in a barebones Grails 2.4.3 application. Is the service transactional? How are you verifying the existence of the new post?

Note that if the service is transactional, the session will be flushed automatically when the method returns. So the explicit flush shouldn't be necessary.

**Comment by ifrankov** [comment]
Hi Peter, 

Is it possible to send me your hubbub project for grails 2.4.3  or 2.4.4.
I have an additional problem. Update in Profile doesn't function. 

Thank you in advance!
Best regards, 
Ivo


Von Samsung Mobile gesendet

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Peter Ledbrook <notifications@github.com> </div><div>Datum:12.01.2015  11:37  (GMT+01:00) </div><div>An: GrailsInAction/graina2 <graina2@noreply.github.com> </div><div>Cc: ifrankov <i.frankov@googlemail.com> </div><div>Betreff: Re: [graina2] MEAP v13, ch6, Issues with PostControllerSpec (Listing
  6.x, Pg. 144) (#64) </div><div>
</div>@ifrankov Unfortunately I can't reproduce this issue in a barebones Grails 2.4.3 application. Is the service transactional? How are you verifying the existence of the new post?

Note that if the service is transactional, the session will be flushed automatically when the method returns. So the explicit flush shouldn't be necessary.

**Comment by ifrankov** [comment]
Hi Peter,

I read that it is a general problem in Grails that byte [] causes problem with scaffolding update.
Is there some workaround.

Best regards,
Ivo

**Comment by pledbrook** [comment]
Not that I'm aware of. byte[] should be represented as a file upload form if I remember correctly.
